# Site settings
title: Andony Landivar Macias
cv: 
email: alandivar@u.northwestern.edu
description: > # this means to ignore newlines until "baseurl:"
  "Learn from yesterday,
  live for today, hope for tomorrow.
  The important thing is not to stop questioning." 
  -- Albert Einstein 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alandivar.github.io" # the base hostname & protocol for your site
twitter_username: andonylandivar
github_username:  alandivar

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Graduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
google_analytics: UA-97213046-2
